### PR TITLE
Update short_description constraint to 30 chars

### PR DESCRIPTION
**Pull request by creativedrewy**
Addresses #195

### CODE REVIEW

**Comment by sdlaver** [comment]
I think we need to do a soft-rollout of this change, since publishers have already started using 50 characters. A warning in the next version, followed by enforcement in the following version.

**Comment by creativedrewy** [comment]
So then, this PR likely should be closed, correct? How should we get the word out about the impending change? Just direct comms, or update the "release notes" section in the CLI here?

**Comment by sdlaver** [comment]
I'd detect between 30 and 50 chars, and print a warning to the CLI. We should add it to that "release notes" blurb we print out when running the tool as well.

**Comment by creativedrewy** [comment]
Love this! Will update

**Comment by creativedrewy** [comment]
Actually, I'm going to revert this PR and start over w/ new requirements

**Pull request closed without merging**
