### PR TITLE
Add a warning message if locale list is over 25

### PR DESCRIPTION
**Pull request by ankur2136**
This warns the developers to configure the locales correctly.

### CODE REVIEW

**Review by creativedrewy — COMMENTED** [review]
I dunno if we need this. @sdlaver what do you think?

**Comment by ankur2136** [comment]
We definitely need this, otherwise every other dApp is claiming to have 85 language support but they dont support anything other than English. Or we need a release section where publishers manually enter the locales they support.

**Comment by creativedrewy** [comment]
Yeah not denying that something like this could be beneficial; I just think @sdlaver will have some thoughts about the appropriate placement/behavior of it.

**Comment by ankur2136** [comment]
The more I think about this it feels inappropriate to ask developers to add `resConfig` to their build files to limit locales. (even if its a good idea in most cases) 

#171 for considering to add locale in the publishing specs.

**Pull request merged**
